### ISSUE TITLE
Innaccurate OpenAPI schema

### ISSUE THREAD

**Issue by amunerato** [akornatskyy/scheduler#519]
Hi everybody,
I noticed that in some API definitions like `POST /jobs` crucial keys like `state`, `schedule` and `name` are set as `readOnly`.
This attribute is hiding them from the OpenAPI rendering in both paths and schema and it generates a wrong body request.
Also, OpenAPI specification states that `readOnly` attribute should be set when a property may be sent as part of a response, but should not be sent as part of the request, so I think that in this case is not applied correctly.
Is there any reason about this choice? I can also fix this and create a pull request if you need.

**Comment by akornatskyy** [comment]
thanks. feel free to submit a pull request, please.
