### ISSUE TITLE
Question: Automatic history cleanup?

### ISSUE THREAD

**Issue by No0Vad** [akornatskyy/scheduler#916]
I've tried looking through the code, but I don't know GO to understand the flow.

I'm wondering if there is an automatic clean-up of the added history for each job?
Or will it just increase and increase over time and you have to manually delete them?

An environment variable for how many days to keep would be a good start, if something is implemented.

**Comment by akornatskyy** [comment]
right now there is no retention policy implemented for the historical records. you have to manually cleanup.
