### ISSUE TITLE
PAUSE ALL - UNPAUSE ALL

### ISSUE THREAD

**Issue by onyxg** [akornatskyy/scheduler#94]
Hi,

This is a lovely job-scheduler tool and has all the features we are looking for!

What are the chances of including a "Pause/Disable All" --- "UnPause/Enable" All buttons...

**Comment by akornatskyy** [comment]
you can use collections for that... e.g. enable/disable corresponding collection of jobs.

**Comment by onyxg** [comment]
awesome, thanks buddy! 👍
