### ISSUE TITLE
Either allow custom commands or allow insecure flag on HTTP Action

### ISSUE THREAD

**Issue by onyxg** [akornatskyy/scheduler#99]
I need to either have custom commands available (looking at the source, its a large change) or we need to have an option/flag to allow insecure flag on the HTTP Action

History
> Get https://push.statuscake.com/?PK=XXXXX&TestID=XXXX&time=0: x509: certificate signed by unknown authority``

**Comment by akornatskyy** [comment]
Unfortunately cannot reproduce this issue, seems like they fixed the certificate issue...

**Comment by jirian** [comment]
Maybe adding this to the Dockerfile would help:
`RUN apk --no-cache add ca-certificates`
